# Generated by Django 4.2.7 on 2025-09-09 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_ip', models.GenericIPAddressField()),
                ('verifier_user_agent', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('suspicious', 'Suspicious'), ('revoked', 'Revoked')], max_length=20)),
                ('ai_fraud_score', models.FloatField(blank=True, null=True)),
                ('ai_fraud_result', models.CharField(blank=True, choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('fraudulent', 'Fraudulent'), ('needs_review', 'Needs Manual Review')], max_length=20, null=True)),
                ('ai_fraud_details', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verification_method', models.CharField(default='api', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='certificates.certificate')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_logs',
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['verified_at'], name='verificatio_verifie_40c07f_idx'), models.Index(fields=['verification_status'], name='verificatio_verific_0ab59e_idx'), models.Index(fields=['ai_fraud_result'], name='verificatio_ai_frau_9067fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('certificate_created', 'Certificate Created'), ('certificate_updated', 'Certificate Updated'), ('certificate_revoked', 'Certificate Revoked'), ('institution_verified', 'Institution Verified'), ('institution_suspended', 'Institution Suspended'), ('verification_performed', 'Verification Performed'), ('fraud_detected', 'Fraud Detected')], max_length=30)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'), models.Index(fields=['action_type'], name='audit_logs_action__168beb_idx'), models.Index(fields=['object_type'], name='audit_logs_object__69dfc3_idx')],
            },
        ),
    ]
