# Generated by Django 4.2.7 on 2025-09-09 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('course_name', models.CharField(max_length=255)),
                ('certificate_type', models.CharField(choices=[('degree', 'Degree Certificate'), ('diploma', 'Diploma Certificate'), ('course', 'Course Completion'), ('achievement', 'Achievement Certificate'), ('participation', 'Participation Certificate')], max_length=20)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_hash', models.CharField(max_length=64)),
                ('blockchain_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('blockchain_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='institutions.institution')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['certificate_id'], name='certificate_certifi_a0a669_idx'), models.Index(fields=['student_email'], name='certificate_student_ef9926_idx'), models.Index(fields=['status'], name='certificate_status_a01db5_idx')],
            },
        ),
    ]
